# frozen_string_literal: true

require_relative '../../../lib/slim_pickins/census'

module WayExam
  Question = Struct.new(:id, :number, :prompt, :options, :correct_key, :explanation, keyword_init: true) do
    def option_a = options[:a]
    def option_b = options[:b]
    def option_c = options[:c]
    def correct_answer = options[correct_key]
  end

  Result = Struct.new(:score, :total, :percentage, :passed, :verdict, :reviews, keyword_init: true)
  Review = Struct.new(:id, :number, :prompt, :user_answer, :correct_answer, :correct, :explanation, keyword_init: true)

  class Exam
    QUESTIONS = [
      Question.new(
        id: 'q1',
        number: 1,
        prompt: 'What is the core morphological rule of alt-slim-pickins?',
        options: {
          a: 'A dot means data, a bare word is language.',
          b: 'Attributes use colon qualifiers like :href.',
          c: 'Double quotes for data, single quotes for words.'
        },
        correct_key: :a,
        explanation: 'PRIMER.md: "A dot means data, a bare word is language. Every value carries a dot (.name), every name does not (products, primary)."'
      ),
      Question.new(
        id: 'q2',
        number: 2,
        prompt: 'How are conditionals idiomatically handled in slim-pickins?',
        options: {
          a: 'Using standard Ruby if/else control tags with <% %>.',
          b: 'Conditionals dissolve into vocabulary (like empty) describing the situation.',
          c: 'Using ternary operators inside attribute strings.'
        },
        correct_key: :b,
        explanation: 'PRIMER.md: "Conditionals dissolve into vocabulary. The language does not have if; it has words that describe the situation."'
      ),
      Question.new(
        id: 'q3',
        number: 3,
        prompt: 'What happens when a collection is iterated via `each account`?',
        options: {
          a: 'A global Ruby variable $account is set across all templates.',
          b: 'You must qualify every child expression as account.balance.',
          c: 'Child sentences resolve dotted attributes (e.g. .balance) directly on that account.'
        },
        correct_key: :c,
        explanation: 'PRIMER.md: "each account iterates accounts and shifts the subject, so child lines read directly on that account."'
      ),
      Question.new(
        id: 'q4',
        number: 4,
        prompt: 'Where do visual styles belong according to the design discipline?',
        options: {
          a: 'In tag style attributes on every DOM element.',
          b: 'In theme roles and word variants, refusing raw inline styles.',
          c: 'In global utility classes generated by a JS build pipeline.'
        },
        correct_key: :b,
        explanation: 'PRIMER.md: "Styles belong to theme roles and word variants. We make machines understand humans; we do not ask humans to speak in CSS machine code."'
      ),
      # The one question whose answer moves. It said `64 words` — and offered no
      # other option a reader could pick, so the true answer was graded wrong and
      # the explanation's breakdown (42 + 22) was wrong in both terms. It claimed
      # to be "held by test", and a test did hold it, at the wrong number, in a
      # suite no gate runs. The count is now computed from the census on load, like
      # every other living vital, so the exam cannot grade a stale answer again.
      # Every option is computed, not just the right one. A hand-written `53` was
      # a latent second correct answer — if the census ever measured 53 the
      # question would have two, and nothing would say so. Each distractor is now
      # a real quantity a reader might confuse for the vocabulary: the Ruby
      # primitives without the partials, and the canonical words with the apps'
      # own words added in.
      Question.new(
        id: 'q5',
        number: 5,
        prompt: 'How many words comprise the alt-slim-pickins vocabulary?',
        options: {
          a: "#{SlimPickins::Census.words[:primitives].size} words",
          b: "#{SlimPickins::Census.words[:total].size + SlimPickins::Census.app_words.size} words",
          c: "#{SlimPickins::Census.words[:total].size} words"
        },
        correct_key: :c,
        explanation: 'bin/census.rb counts the vocabulary from the tree: ' \
                     "#{SlimPickins::Census.words[:primitives].size} Ruby primitives + " \
                     "#{SlimPickins::Census.words[:partials].size} .sp partials. " \
                     'Measured, not recorded — which is why this option is computed too.'
      )
    ].freeze

    def self.questions
      QUESTIONS
    end

    def self.find(id)
      QUESTIONS.find { |q| q.id == id.to_s }
    end

    def self.sample_answers
      {
        'q1' => 'a',
        'q2' => 'b',
        'q3' => 'c',
        'q4' => 'b',
        'q5' => 'c'
      }
    end

    def self.grade(answers = {})
      reviews = QUESTIONS.map do |q|
        raw_ans = answers[q.id] || answers[q.id.to_sym]
        user_key = raw_ans.to_s.strip.downcase.to_sym
        resolved_text = q.options[user_key] || raw_ans.to_s.strip

        correct = (user_key == q.correct_key) || (resolved_text == q.correct_answer)
        display_user_answer = resolved_text.empty? ? '(No answer)' : resolved_text

        Review.new(
          id: q.id,
          number: q.number,
          prompt: q.prompt,
          user_answer: display_user_answer,
          correct_answer: q.correct_answer,
          correct: correct,
          explanation: q.explanation
        )
      end

      score = reviews.count(&:correct)
      total = QUESTIONS.size
      percentage = ((score.to_f / total) * 100).round
      passed = percentage >= 80
      verdict = if percentage == 100
                  'Master of the Way'
                elsif passed
                  'Apprentice of the Way'
                else
                  'Needs Re-reading'
                end

      Result.new(
        score: score,
        total: total,
        percentage: percentage,
        passed: passed,
        verdict: verdict,
        reviews: reviews
      )
    end
  end
end
